"""Update wmi table

Revision ID: 2ab0dc6c9850
Revises: 49ac5f7e7d07
Create Date: 2022-06-17 12:48:24.611103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab0dc6c9850'
down_revision = '49ac5f7e7d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wmi_action', sa.Column('wmi_query', sa.String(length=64), nullable=True))
    op.drop_index('ix_wmi_action_wmi_attributes', table_name='wmi_action')
    op.drop_index('ix_wmi_action_wmi_class', table_name='wmi_action')
    op.drop_index('ix_wmi_action_wmi_scope', table_name='wmi_action')
    op.create_index(op.f('ix_wmi_action_wmi_query'), 'wmi_action', ['wmi_query'], unique=True)
    op.drop_column('wmi_action', 'wmi_scope')
    op.drop_column('wmi_action', 'wmi_class')
    op.drop_column('wmi_action', 'wmi_attributes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wmi_action', sa.Column('wmi_attributes', sa.VARCHAR(length=128), nullable=True))
    op.add_column('wmi_action', sa.Column('wmi_class', sa.VARCHAR(length=64), nullable=True))
    op.add_column('wmi_action', sa.Column('wmi_scope', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_wmi_action_wmi_query'), table_name='wmi_action')
    op.create_index('ix_wmi_action_wmi_scope', 'wmi_action', ['wmi_scope'], unique=False)
    op.create_index('ix_wmi_action_wmi_class', 'wmi_action', ['wmi_class'], unique=False)
    op.create_index('ix_wmi_action_wmi_attributes', 'wmi_action', ['wmi_attributes'], unique=False)
    op.drop_column('wmi_action', 'wmi_query')
    # ### end Alembic commands ###
