"""Remove WMIAction attribute

Revision ID: 98ae79407b03
Revises: 49ac5f7e7d07
Create Date: 2022-06-18 15:05:03.126019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ae79407b03'
down_revision = '49ac5f7e7d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wmi_action_wmi_attributes', table_name='wmi_action')
    op.drop_index('ix_wmi_action_wmi_class', table_name='wmi_action')
    op.create_index(op.f('ix_wmi_action_wmi_class'), 'wmi_action', ['wmi_class'], unique=True)
    op.drop_column('wmi_action', 'wmi_attributes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wmi_action', sa.Column('wmi_attributes', sa.VARCHAR(length=128), nullable=True))
    op.drop_index(op.f('ix_wmi_action_wmi_class'), table_name='wmi_action')
    op.create_index('ix_wmi_action_wmi_class', 'wmi_action', ['wmi_class'], unique=False)
    op.create_index('ix_wmi_action_wmi_attributes', 'wmi_action', ['wmi_attributes'], unique=False)
    # ### end Alembic commands ###
