"""Add association table for many-to-many connection

Revision ID: d6f99a32b57d
Revises: 84baa3df9edc
Create Date: 2022-04-22 15:30:53.043417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f99a32b57d'
down_revision = '84baa3df9edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_wmiAction',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('wmi_action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['wmi_action_id'], ['wmi_action.id'], )
    )
    op.add_column('wmi_action', sa.Column('id', sa.String(length=64), nullable=False))
    op.drop_column('wmi_action', 'action_id')
    op.drop_column('wmi_action', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wmi_action', sa.Column('client_id', sa.INTEGER(), nullable=True))
    op.add_column('wmi_action', sa.Column('action_id', sa.VARCHAR(length=64), nullable=False))
    op.drop_column('wmi_action', 'id')
    op.drop_table('client_wmiAction')
    # ### end Alembic commands ###
