"""OS and wmi_attributes can't be unique

Revision ID: 49ac5f7e7d07
Revises: a31690e553c6
Create Date: 2022-04-23 09:52:21.371082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ac5f7e7d07'
down_revision = 'a31690e553c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_os_name', table_name='client')
    op.create_index(op.f('ix_client_os_name'), 'client', ['os_name'], unique=False)
    op.drop_index('ix_wmi_action_wmi_scope', table_name='wmi_action')
    op.create_index(op.f('ix_wmi_action_wmi_scope'), 'wmi_action', ['wmi_scope'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wmi_action_wmi_scope'), table_name='wmi_action')
    op.create_index('ix_wmi_action_wmi_scope', 'wmi_action', ['wmi_scope'], unique=False)
    op.drop_index(op.f('ix_client_os_name'), table_name='client')
    op.create_index('ix_client_os_name', 'client', ['os_name'], unique=False)
    # ### end Alembic commands ###
