"""Client connects to WMIAction table

Revision ID: 84baa3df9edc
Revises: a0f3270c6e09
Create Date: 2022-04-22 00:41:58.490667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84baa3df9edc'
down_revision = 'a0f3270c6e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wmi_action', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wmi_action', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wmi_action', type_='foreignkey')
    op.drop_column('wmi_action', 'client_id')
    # ### end Alembic commands ###
