"""wmi_attributes not unique

Revision ID: a31690e553c6
Revises: ff8106be942d
Create Date: 2022-04-22 18:56:23.362748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31690e553c6'
down_revision = 'ff8106be942d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wmi_action_wmi_attributes', table_name='wmi_action')
    op.create_index(op.f('ix_wmi_action_wmi_attributes'), 'wmi_action', ['wmi_attributes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wmi_action_wmi_attributes'), table_name='wmi_action')
    op.create_index('ix_wmi_action_wmi_attributes', 'wmi_action', ['wmi_attributes'], unique=False)
    # ### end Alembic commands ###
